# model_name_or_path: google/gemma-3-4b-it
model_name_or_path: google/gemma-3-12b-it

dataset_dir: dataset/African-Proverbs/Data
template_name: gemma
# location: "Kenya, Somali"
# language: "kamba, maasai, nubian, nubian_2, luo, gikuyu, ekegusii, digo; somali"
location: "Kenya, Ethiopia, Somali, Tanzania, Uganda, DRC"
language: "kamba, maasai, nubian, nubian_2, luo, gikuyu, ekegusii, digo; borana; somali; gweno, kihangaza, kihara, nyaturu, pare, zigula; alur, chiga; bangubangu, hema"

task_class: eval
task_type: "gen_eng_literal"

num_train_epochs: 10
predict_with_generate: True
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
report_to: none
remove_unused_columns: False
ddp_find_unused_parameters: False
save_strategy: steps
save_steps: 1000
save_total_limit: 1
logging_steps: 50
# eval_strategy: "steps"
# eval_steps: 1000
learning_rate: 1.0e-5
dataloader_num_workers: 4
lr_scheduler_type: cosine
output_dir: outputs/gemma3-12b-it-gen-eng-literal
